import { Dimension, DimensionMeta, Question } from './types';

export const DIMENSIONS: Dimension[] = ['M', 'A', 'I', 'G', 'E', 'T'];

export const DIMENSION_META: Record<Dimension, DimensionMeta> = {
  M: {
    id: 'M',
    name: 'Provision',
    score0End: 'Public provision',
    score100End: 'Markets',
    whatItDescribes: 'Preference for public delivery versus competing private providers in the scenarios shown.',
    whatItDoesNotEstablish: 'Whether the person wants an effective state, cares about poverty, or supports every business.',
    shareLineLow: 'Build in public hands',
    shareLineHigh: 'Let providers compete',
    strongTraitLow: 'PUBLIC PROVISION',
    strongTraitHigh: 'MARKETS',
    publicName: 'public services',
  },
  A: {
    id: 'A',
    name: 'Freedom',
    score0End: 'Social order',
    score100End: 'Autonomy',
    whatItDescribes: 'Willingness to protect individual choice when it imposes inconvenience, offence, or risk on others.',
    whatItDoesNotEstablish: 'Whether the person is kind, selfish, or approves of the protected behavior.',
    shareLineLow: 'Keep shared rules strong',
    shareLineHigh: 'Leave room for personal choice',
    strongTraitLow: 'SOCIAL ORDER',
    strongTraitHigh: 'AUTONOMY',
    publicName: 'personal freedom',
  },
  I: {
    id: 'I',
    name: 'Institutions',
    score0End: 'Challenge institutions',
    score100End: 'Trust institutions',
    whatItDescribes: 'Willingness to defer to established institutions versus seek outside checks or replacement.',
    whatItDoesNotEstablish: 'Expertise, support for democracy, conspiratorial beliefs, or state capacity.',
    shareLineLow: 'Make power earn your trust',
    shareLineHigh: 'Work through the institutions',
    strongTraitLow: 'INSTITUTIONAL SCEPTICISM',
    strongTraitHigh: 'INSTITUTIONAL TRUST',
    publicName: 'institutions',
  },
  G: {
    id: 'G',
    name: 'Belonging',
    score0End: 'National priority',
    score100End: 'Global concern',
    whatItDescribes: 'How much national membership should change cooperation, opportunity, and obligations.',
    whatItDoesNotEstablish: 'Ethnicity, personal tolerance, or feelings about every border policy.',
    shareLineLow: 'Responsibility starts at home',
    shareLineHigh: 'Look beyond the border',
    strongTraitLow: 'NATIONAL PRIORITY',
    strongTraitHigh: 'GLOBAL CONCERN',
    publicName: 'national priorities',
  },
  E: {
    id: 'E',
    name: 'Distribution',
    score0End: 'Unequal rewards',
    score100End: 'Equal outcomes',
    whatItDescribes: 'Preference for reducing differences in resources versus allowing rewards and inheritance to create larger differences.',
    whatItDoesNotEstablish: 'Work ethic, personal generosity, or belief that all inequality is deserved.',
    shareLineLow: 'Let the rewards differ',
    shareLineHigh: 'Close the gaps',
    strongTraitLow: 'UNEQUAL REWARDS',
    strongTraitHigh: 'EQUALITY',
    publicName: 'distribution',
  },
  T: {
    id: 'T',
    name: 'Change',
    score0End: 'Precaution',
    score100End: 'Acceleration',
    whatItDescribes: 'Willingness to introduce new technology under uncertainty versus wait for more evidence.',
    whatItDoesNotEstablish: 'Technical knowledge, support for a particular company, or confidence that technology always helps.',
    shareLineLow: 'Prove it before scaling it',
    shareLineHigh: 'Try it, watch it, learn',
    strongTraitLow: 'PRECAUTION',
    strongTraitHigh: 'ACCELERATION',
    publicName: 'technology',
  },
};

export const CORE_QUESTION_SEQUENCE: string[] = [
  'M1', 'A1', 'I1', 'G1', 'E1', 'T1',
  'M2', 'A2', 'I2', 'G2', 'E2', 'T2',
  'M3', 'A3', 'I3', 'G3', 'E3', 'T3',
];

export const QUESTION_BANK: Record<string, Question> = {
  // M: Provision
  M1: {
    id: 'M1',
    dimension: 'M',
    phase: 'core',
    context: 'Housing',
    prompt: "Housing costs have become unaffordable for many residents in your city. What approach should take priority?",
    choices: {
      A: "Ease zoning restrictions so private homebuilders can expand the housing supply.",
      B: "Invest public funds into developing social and non-profit municipal housing.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  M2: {
    id: 'M2',
    dimension: 'M',
    phase: 'core',
    context: 'Transport',
    prompt: "The regional rail network faces persistent delays and capacity issues. How should it be managed?",
    choices: {
      A: "A unified public transport authority to coordinate service and maintain public accountability.",
      B: "Competing private operators to drive efficiency and give passengers consumer choice.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  M3: {
    id: 'M3',
    dimension: 'M',
    phase: 'core',
    context: 'Internet',
    prompt: "High-speed internet in your area is expensive and service is inconsistent. What is the best remedy?",
    choices: {
      A: "Treat internet access as a public utility and build a municipal network for all residents.",
      B: "Lower regulatory barriers so private providers can enter the market and compete on price.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  M4: {
    id: 'M4',
    dimension: 'M',
    phase: 'optional',
    context: 'Childcare',
    prompt: "New funding is approved to lower childcare costs for families. Where should the resources go?",
    choices: {
      A: "Direct subsidies that parents can spend at accredited childcare providers of their choice.",
      B: "Expanding the network of publicly funded community childcare centers.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  M5: {
    id: 'M5',
    dimension: 'M',
    phase: 'optional',
    context: 'Electricity',
    prompt: "A region is modernizing its electrical power grid. How should power generation be organized?",
    choices: {
      A: "Independent energy producers competing to supply electricity at market rates.",
      B: "A unified public utility with energy rates regulated by public representatives.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },

  // A: Freedom
  A1: {
    id: 'A1',
    dimension: 'A',
    phase: 'core',
    context: 'Protest',
    prompt: "A peaceful protest march blocks a major highway during the morning commute.",
    choices: {
      A: "Clear the roadway promptly to restore public transit and emergency access.",
      B: "Allow the demonstration to continue, recognizing that effective protest often causes disruption.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  A2: {
    id: 'A2',
    dimension: 'A',
    phase: 'core',
    context: 'Speech',
    prompt: "A publicly funded cultural center schedules a performer whose routine draws intense community protest.",
    choices: {
      A: "Allow the performance to proceed, protecting artistic freedom from public vetoes.",
      B: "Cancel the performance, ensuring public resources are not used to promote offensive content.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  A3: {
    id: 'A3',
    dimension: 'A',
    phase: 'core',
    context: 'Surveillance',
    prompt: "City authorities propose installing automated facial-recognition cameras in busy public plazas to track suspects.",
    choices: {
      A: "Restrict the technology to protect citizens from pervasive surveillance in everyday life.",
      B: "Deploy the technology to assist law enforcement in preventing crime and locating dangerous offenders.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  A4: {
    id: 'A4',
    dimension: 'A',
    phase: 'optional',
    context: 'Nightlife',
    prompt: "Downtown entertainment venues drive nightlife and jobs, but create late-night noise for nearby residents.",
    choices: {
      A: "Enforce nighttime noise limits to protect residents' quality of life and rest.",
      B: "Permit late operating hours to foster cultural life and a vibrant nighttime economy.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  A5: {
    id: 'A5',
    dimension: 'A',
    phase: 'optional',
    context: 'Personal risk',
    prompt: "An extreme combat sport carries a high rate of severe long-term brain injury.",
    choices: {
      A: "Regulate or restrict the sport to prevent severe, irreversible neurological damage.",
      B: "Allow informed adults to participate, respecting individual freedom over personal risk.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },

  // I: Institutions
  I1: {
    id: 'I1',
    dimension: 'I',
    phase: 'core',
    context: 'Regulators',
    prompt: "A national health regulator declares an ingredient safe, but critics raise questions.",
    choices: {
      A: "Accept the regulator's findings, placing trust in established scientific standards and institutional review.",
      B: "Withhold endorsement until independent researchers outside the agency replicate and confirm safety.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  I2: {
    id: 'I2',
    dimension: 'I',
    phase: 'core',
    context: 'Political leadership',
    prompt: "Two candidates propose similar reforms to improve public administration. Whose approach do you prefer?",
    choices: {
      A: "An independent outsider unconstrained by established routines and willing to challenge bureaucracy.",
      B: "An experienced administrator with institutional knowledge who knows how to navigate government processes.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  I3: {
    id: 'I3',
    dimension: 'I',
    phase: 'core',
    context: 'Agency leadership',
    prompt: "A public development agency repeatedly misses its project targets. How should its leadership be restructured?",
    choices: {
      A: "Appoint career administrators with expertise in public management to reorganize operations.",
      B: "Transfer oversight to a council of local community members to align decisions with resident needs.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  I4: {
    id: 'I4',
    dimension: 'I',
    phase: 'optional',
    context: 'Accountability',
    prompt: "A major corruption scandal is uncovered inside city government. Who should lead the inquiry?",
    choices: {
      A: "An independent citizens' assembly to ensure an inquiry free from bureaucratic loyalty.",
      B: "The official statutory integrity watchdog with legal authority and investigative expertise.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  I5: {
    id: 'I5',
    dimension: 'I',
    phase: 'optional',
    context: 'Courts',
    prompt: "A high court strikes down an overwhelmingly popular new law on constitutional grounds. Who gets the final say?",
    choices: {
      A: "The judiciary, to uphold constitutional principles and protect minority rights against majorities.",
      B: "The electorate, ensuring ultimate democratic sovereignty rests with the voting public.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },

  // G: Belonging
  G1: {
    id: 'G1',
    dimension: 'G',
    phase: 'core',
    context: 'Work',
    prompt: "An employer has an open position with two equally qualified finalists: a domestic citizen and a foreign applicant.",
    choices: {
      A: "Prioritize the domestic citizen to support national employment and local communities.",
      B: "Select based entirely on individual qualifications, considering nationality irrelevant to the role.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  G2: {
    id: 'G2',
    dimension: 'G',
    phase: 'core',
    context: 'Aid',
    prompt: "A critical medical treatment is in severely limited supply during an international outbreak.",
    choices: {
      A: "Distribute supplies internationally based on where health needs and infection rates are most severe.",
      B: "Prioritize supplying the domestic population first, fulfilling the government's primary duty to its citizens.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  G3: {
    id: 'G3',
    dimension: 'G',
    phase: 'core',
    context: 'Cooperation',
    prompt: "An international environmental agreement mandates emissions reductions that will increase costs for domestic manufacturers.",
    choices: {
      A: "Commit to the treaty, recognizing that global environmental challenges require shared international obligations.",
      B: "Decline binding commitments to protect domestic industrial competitiveness and preserve national discretion.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  G4: {
    id: 'G4',
    dimension: 'G',
    phase: 'optional',
    context: 'Refuge',
    prompt: "Refugees fleeing armed conflict arrive at the border, while local public infrastructure is already strained.",
    choices: {
      A: "Pace admissions to match local housing and healthcare capacity, ensuring sustainable integration.",
      B: "Accept them under humanitarian obligations and mobilize emergency public resources to accommodate them.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  G5: {
    id: 'G5',
    dimension: 'G',
    phase: 'optional',
    context: 'Trade',
    prompt: "A municipal infrastructure project needs steel. Domestic suppliers cost 30% more than identical foreign imports.",
    choices: {
      A: "Purchase domestically to support local industrial capacity and domestic manufacturing jobs.",
      B: "Purchase the lower-cost imports to maximize public funds and transit construction.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },

  // E: Distribution
  E1: {
    id: 'E1',
    dimension: 'E',
    phase: 'core',
    context: 'Inheritance',
    prompt: "A wealthy business owner passes away, leaving a large estate to their children.",
    choices: {
      A: "Levy a substantial inheritance tax to reduce wealth concentration and invest in public opportunities.",
      B: "Allow the family to inherit the estate with minimal tax, protecting private property and family provision.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  E2: {
    id: 'E2',
    dimension: 'E',
    phase: 'core',
    context: 'Rewards',
    prompt: "A team successfully completes a demanding project, with all members contributing but a few taking on substantially greater responsibility.",
    choices: {
      A: "Distribute the team bonus pool equally to reinforce collaborative teamwork and shared ownership.",
      B: "Allocate the largest share of the bonus to the lead contributors to recognize outsized effort.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  E3: {
    id: 'E3',
    dimension: 'E',
    phase: 'core',
    context: 'Opportunity',
    prompt: "A major university has a limited number of full-tuition scholarships available.",
    choices: {
      A: "Award them strictly on academic achievement and test performance to recognize intellectual excellence.",
      B: "Award them to talented students from lower-income backgrounds to promote socioeconomic mobility.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  E4: {
    id: 'E4',
    dimension: 'E',
    phase: 'optional',
    context: 'Pay gaps',
    prompt: "A major corporation's CEO receives compensation hundreds of times higher than the median employee.",
    choices: {
      A: "Cap the executive-to-worker pay ratio by law to limit internal workplace inequality.",
      B: "Let corporate boards determine executive compensation based on competitive market rates and performance.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  E5: {
    id: 'E5',
    dimension: 'E',
    phase: 'optional',
    context: 'Shared resources',
    prompt: "A municipal council has surplus funds to allocate for youth athletic programs.",
    choices: {
      A: "Fund specialized coaching and competitive facilities to cultivate top athletic talent.",
      B: "Fund free community programs and gear to maximize broad participation for all youth.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },

  // T: Change
  T1: {
    id: 'T1',
    dimension: 'T',
    phase: 'core',
    context: 'Transport technology',
    prompt: "Self-driving passenger shuttles perform reliably in closed testing, but have limited data in live urban traffic.",
    choices: {
      A: "Launch a live, monitored pilot on public streets to accelerate real-world testing and deployment.",
      B: "Keep testing in controlled conditions until safety benchmarks are verified before public street use.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  T2: {
    id: 'T2',
    dimension: 'T',
    phase: 'core',
    context: 'Education technology',
    prompt: "An interactive AI learning assistant improves student test results, but its long-term impact on learning habits is unstudied.",
    choices: {
      A: "Hold off on classroom adoption until long-term educational studies evaluate potential unintended effects.",
      B: "Integrate it into classrooms now to capture immediate educational gains while tracking student progress.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  T3: {
    id: 'T3',
    dimension: 'T',
    phase: 'core',
    context: 'Food technology',
    prompt: "Lab-cultivated meat meets baseline regulatory standards. When should it be made available to consumers?",
    choices: {
      A: "Approve it for commercial sale with clear labeling, allowing consumers to make their own choices.",
      B: "Withhold market approval until multi-year nutritional and health studies confirm long-term safety.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  T4: {
    id: 'T4',
    dimension: 'T',
    phase: 'optional',
    context: 'Infrastructure technology',
    prompt: "A coastal city faces escalating flood risks. Engineers propose an unproven, advanced barrier design.",
    choices: {
      A: "Rely on proven barrier techniques with established, documented performance records.",
      B: "Install the advanced experimental design to pursue potentially superior flood protection.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  T5: {
    id: 'T5',
    dimension: 'T',
    phase: 'optional',
    context: 'Workplace technology',
    prompt: "A new generative AI tool cuts office documentation time in half, but occasionally outputs convincing factual errors.",
    choices: {
      A: "Deploy the tool across teams with human review requirements to capture productivity benefits.",
      B: "Restrict its use in core workflows until accuracy and verification standards can be reliably met.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
};
