import { Dimension, DimensionMeta, Question } from './types';

export const DIMENSIONS: Dimension[] = ['M', 'A', 'I', 'G', 'E', 'T'];

export const DIMENSION_META: Record<Dimension, DimensionMeta> = {
  M: {
    id: 'M',
    name: 'Provision',
    score0End: 'Public provision',
    score100End: 'Markets',
    whatItDescribes: 'Preference for public delivery versus competing private providers in the scenarios shown.',
    whatItDoesNotEstablish: 'Whether the person wants an effective state, cares about poverty, or supports every business.',
    shareLineLow: 'Build in public hands',
    shareLineHigh: 'Let providers compete',
    strongTraitLow: 'PUBLIC PROVISION',
    strongTraitHigh: 'MARKETS',
    publicName: 'public services',
  },
  A: {
    id: 'A',
    name: 'Freedom',
    score0End: 'Social order',
    score100End: 'Autonomy',
    whatItDescribes: 'Willingness to protect individual choice when it imposes inconvenience, offence, or risk on others.',
    whatItDoesNotEstablish: 'Whether the person is kind, selfish, or approves of the protected behavior.',
    shareLineLow: 'Keep shared rules strong',
    shareLineHigh: 'Leave room for personal choice',
    strongTraitLow: 'SOCIAL ORDER',
    strongTraitHigh: 'AUTONOMY',
    publicName: 'personal freedom',
  },
  I: {
    id: 'I',
    name: 'Institutions',
    score0End: 'Challenge institutions',
    score100End: 'Trust institutions',
    whatItDescribes: 'Willingness to defer to established institutions versus seek outside checks or replacement.',
    whatItDoesNotEstablish: 'Expertise, support for democracy, conspiratorial beliefs, or state capacity.',
    shareLineLow: 'Make power earn your trust',
    shareLineHigh: 'Work through the institutions',
    strongTraitLow: 'INSTITUTIONAL SCEPTICISM',
    strongTraitHigh: 'INSTITUTIONAL TRUST',
    publicName: 'institutions',
  },
  G: {
    id: 'G',
    name: 'Belonging',
    score0End: 'National priority',
    score100End: 'Global concern',
    whatItDescribes: 'How much national membership should change cooperation, opportunity, and obligations.',
    whatItDoesNotEstablish: 'Ethnicity, personal tolerance, or feelings about every border policy.',
    shareLineLow: 'Responsibility starts at home',
    shareLineHigh: 'Look beyond the border',
    strongTraitLow: 'NATIONAL PRIORITY',
    strongTraitHigh: 'GLOBAL CONCERN',
    publicName: 'national priorities',
  },
  E: {
    id: 'E',
    name: 'Distribution',
    score0End: 'Unequal rewards',
    score100End: 'Equal outcomes',
    whatItDescribes: 'Preference for reducing differences in resources versus allowing rewards and inheritance to create larger differences.',
    whatItDoesNotEstablish: 'Work ethic, personal generosity, or belief that all inequality is deserved.',
    shareLineLow: 'Let the rewards differ',
    shareLineHigh: 'Close the gaps',
    strongTraitLow: 'UNEQUAL REWARDS',
    strongTraitHigh: 'EQUALITY',
    publicName: 'distribution',
  },
  T: {
    id: 'T',
    name: 'Change',
    score0End: 'Precaution',
    score100End: 'Acceleration',
    whatItDescribes: 'Willingness to introduce new technology under uncertainty versus wait for more evidence.',
    whatItDoesNotEstablish: 'Technical knowledge, support for a particular company, or confidence that technology always helps.',
    shareLineLow: 'Prove it before scaling it',
    shareLineHigh: 'Try it, watch it, learn',
    strongTraitLow: 'PRECAUTION',
    strongTraitHigh: 'ACCELERATION',
    publicName: 'technology',
  },
};

export const CORE_QUESTION_SEQUENCE: string[] = [
  'M1', 'A1', 'I1', 'G1', 'E1', 'T1',
  'M2', 'A2', 'I2', 'G2', 'E2', 'T2',
  'M3', 'A3', 'I3', 'G3', 'E3', 'T3',
];

export const QUESTION_BANK: Record<string, Question> = {
  // M: Provision
  M1: {
    id: 'M1',
    dimension: 'M',
    phase: 'core',
    context: 'Housing',
    prompt: "Rent is spiraling out of control in your city. What should happen first?",
    choices: {
      A: "Deregulate zoning so private developers can build more housing.",
      B: "Use public tax dollars to build government-owned housing.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  M2: {
    id: 'M2',
    dimension: 'M',
    phase: 'core',
    context: 'Transport',
    prompt: "The commuter rail network is constantly delayed and overcrowded. Who should run it?",
    choices: {
      A: "A single public operator accountable directly to voters.",
      B: "Competing private rail operators with riders choosing between them.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  M3: {
    id: 'M3',
    dimension: 'M',
    phase: 'core',
    context: 'Internet',
    prompt: "Broadband in your town is overpriced and sluggish. What is the best fix?",
    choices: {
      A: "Treat internet access as a public utility and build a municipal network.",
      B: "Cut red tape so new private telecoms can enter and compete.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  M4: {
    id: 'M4',
    dimension: 'M',
    phase: 'optional',
    context: 'Childcare',
    prompt: "New funding is approved to lower childcare costs for parents. Where should the money go?",
    choices: {
      A: "Direct vouchers that parents can spend at private daycares of their choice.",
      B: "Expanding the network of free, publicly run community childcare centers.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  M5: {
    id: 'M5',
    dimension: 'M',
    phase: 'optional',
    context: 'Electricity',
    prompt: "A region is rebuilding its electrical power grid from scratch. How should energy be supplied?",
    choices: {
      A: "Independent power companies competing to sell electricity at market rates.",
      B: "A unified state utility with electricity prices set by elected officials.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },

  // A: Freedom
  A1: {
    id: 'A1',
    dimension: 'A',
    phase: 'core',
    context: 'Protest',
    prompt: "A peaceful climate protest brings morning highway traffic to a standstill for hours.",
    choices: {
      A: "Clear the road immediately so everyday commuters can get through.",
      B: "Let the demonstration continue. Effective protest is disruptive by nature.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  A2: {
    id: 'A2',
    dimension: 'A',
    phase: 'core',
    context: 'Speech',
    prompt: "A publicly funded theater books a comedian whose routine sparks intense public outrage.",
    choices: {
      A: "Keep the show. People who dislike the material are free not to buy tickets.",
      B: "Cancel the performance. Public institutions shouldn't platform offensive material.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  A3: {
    id: 'A3',
    dimension: 'A',
    phase: 'core',
    context: 'Surveillance',
    prompt: "Local police want to install live facial-recognition cameras across downtown plazas to catch fugitives.",
    choices: {
      A: "Ban the cameras. Citizens have a right to walk through public spaces without warrantless tracking.",
      B: "Deploy the system. Public safety is more important than anonymity in open streets.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  A4: {
    id: 'A4',
    dimension: 'A',
    phase: 'optional',
    context: 'Nightlife',
    prompt: "Downtown bars and clubs drive nightlife and jobs, but keep local residents awake until 4 AM.",
    choices: {
      A: "Enforce strict midnight noise curfews so neighborhood residents can get sleep.",
      B: "Protect late operating hours. Vibrant nightlife is part of living in an energetic city.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  A5: {
    id: 'A5',
    dimension: 'A',
    phase: 'optional',
    context: 'Personal risk',
    prompt: "An extreme combat sport carries a high rate of severe long-term brain injury.",
    choices: {
      A: "Ban or heavily restrict the sport to protect fighters from catastrophic harm.",
      B: "Allow consenting adults to participate as long as they understand the dangers.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },

  // I: Institutions
  I1: {
    id: 'I1',
    dimension: 'I',
    phase: 'core',
    context: 'Regulators',
    prompt: "A government agency declares a controversial new food additive safe for general consumption.",
    choices: {
      A: "Trust the agency's safety clearance unless peer-reviewed counter-evidence emerges.",
      B: "Remain skeptical until the ingredient is independently verified outside the agency.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  I2: {
    id: 'I2',
    dimension: 'I',
    phase: 'core',
    context: 'Political leadership',
    prompt: "Two candidates promise identical reforms to fix broken public services. Who gets your vote?",
    choices: {
      A: "An anti-establishment outsider eager to disrupt entrenched political institutions.",
      B: "An experienced insider who knows how to work the levers of government from within.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  I3: {
    id: 'I3',
    dimension: 'I',
    phase: 'core',
    context: 'Agency leadership',
    prompt: "A state housing authority repeatedly fails to meet its construction targets for years.",
    choices: {
      A: "Bring in veteran civil servants with proven track records in public administration.",
      B: "Replace executive leadership with a citizen council made up of local residents.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  I4: {
    id: 'I4',
    dimension: 'I',
    phase: 'optional',
    context: 'Accountability',
    prompt: "A major corruption scandal is uncovered inside City Hall. Who should lead the inquiry?",
    choices: {
      A: "A citizens' panel randomly selected from the general public like a jury.",
      B: "The state's established, independent anti-corruption watchdog.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  I5: {
    id: 'I5',
    dimension: 'I',
    phase: 'optional',
    context: 'Courts',
    prompt: "A high court strikes down an overwhelmingly popular new law on constitutional grounds. Who gets the final say?",
    choices: {
      A: "The judges. Constitutional limits exist to prevent the majority from overreaching.",
      B: "The voters. A direct citizen referendum should be able to override the bench.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },

  // G: Belonging
  G1: {
    id: 'G1',
    dimension: 'G',
    phase: 'core',
    context: 'Work',
    prompt: "A company has an open position with two equally qualified finalists: a domestic citizen and an international worker.",
    choices: {
      A: "Give preference to the domestic citizen.",
      B: "Hire purely on merit, treating borders and nationality as irrelevant.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  G2: {
    id: 'G2',
    dimension: 'G',
    phase: 'core',
    context: 'Aid',
    prompt: "A life-saving vaccine is in critically short supply during an international epidemic.",
    choices: {
      A: "Distribute doses globally based strictly on where the outbreak is deadliest.",
      B: "Inoculate the domestic population first before exporting doses abroad.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  G3: {
    id: 'G3',
    dimension: 'G',
    phase: 'core',
    context: 'Cooperation',
    prompt: "An international climate treaty requires binding emissions cuts that will hurt domestic manufacturing.",
    choices: {
      A: "Sign the treaty. Global climate stability requires shared sacrifice across borders.",
      B: "Refuse binding limits. Protecting national industry and sovereign autonomy comes first.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  G4: {
    id: 'G4',
    dimension: 'G',
    phase: 'optional',
    context: 'Refuge',
    prompt: "Refugees fleeing war arrive at the border, but local housing and healthcare facilities are already stretched thin.",
    choices: {
      A: "Cap intake until domestic infrastructure and local communities can catch up.",
      B: "Welcome them in and urgently expand emergency capacity to meet the need.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  G5: {
    id: 'G5',
    dimension: 'G',
    phase: 'optional',
    context: 'Trade',
    prompt: "A public transit project needs steel. Local manufacturers cost 30% more than identical foreign imports.",
    choices: {
      A: "Buy domestic to protect local manufacturing jobs and industrial capacity.",
      B: "Buy the cheaper imports and reinvest the savings into transit expansion.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },

  // E: Distribution
  E1: {
    id: 'E1',
    dimension: 'E',
    phase: 'core',
    context: 'Inheritance',
    prompt: "A billionaire passes away, leaving an immense fortune to their children.",
    choices: {
      A: "Tax the vast majority of it to fund universal opportunity grants for young people.",
      B: "Let the family keep what was built. People have a fundamental right to pass wealth to their children.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  E2: {
    id: 'E2',
    dimension: 'E',
    phase: 'core',
    context: 'Rewards',
    prompt: "A product launch exceeds all targets, but two team members did 80% of the actual heavy lifting.",
    choices: {
      A: "Split the team bonus equally among all members.",
      B: "Give the lion's share of the bonus to the two standout contributors.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  E3: {
    id: 'E3',
    dimension: 'E',
    phase: 'core',
    context: 'Opportunity',
    prompt: "A prestigious university has a limited quota of full-ride scholarships.",
    choices: {
      A: "Award them to the applicants with the highest academic test scores.",
      B: "Award them to capable students from low-income families who couldn't otherwise afford college.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  E4: {
    id: 'E4',
    dimension: 'E',
    phase: 'optional',
    context: 'Pay gaps',
    prompt: "A corporation's CEO takes home 300 times the salary of the median worker.",
    choices: {
      A: "Cap the maximum pay ratio by law, even if companies complain it repels top talent.",
      B: "Allow the board to set pay according to market value and executive performance.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  E5: {
    id: 'E5',
    dimension: 'E',
    phase: 'optional',
    context: 'Shared resources',
    prompt: "A town council has surplus recreation funds to allocate for youth sports.",
    choices: {
      A: "Invest in elite facilities and specialized coaching to develop championship talent.",
      B: "Provide free equipment and access so every child in town can participate.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },

  // T: Change
  T1: {
    id: 'T1',
    dimension: 'T',
    phase: 'core',
    context: 'Transport technology',
    prompt: "Self-driving commuter shuttles pass closed-course tests, but have zero miles in chaotic city traffic.",
    choices: {
      A: "Launch a live, monitored pilot on city streets immediately.",
      B: "Hold off until the technology proves its safety through years of additional testing.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  T2: {
    id: 'T2',
    dimension: 'T',
    phase: 'core',
    context: 'Education technology',
    prompt: "An AI tutor sharply improves students' math scores, but its long-term psychological impact is unknown.",
    choices: {
      A: "Wait for comprehensive multi-year longitudinal studies before bringing it into classrooms.",
      B: "Offer it as an optional learning tool now and track students' development in real time.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  T3: {
    id: 'T3',
    dimension: 'T',
    phase: 'core',
    context: 'Food technology',
    prompt: "Cultivated lab-grown meat passes baseline food safety checks. When should it be sold in supermarkets?",
    choices: {
      A: "Approve it for store shelves right away with prominent labels.",
      B: "Require long-term generational dietary studies before permitting commercial sale.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  T4: {
    id: 'T4',
    dimension: 'T',
    phase: 'optional',
    context: 'Infrastructure technology',
    prompt: "A coastal city faces worse flooding every year. Engineers propose an unproven, revolutionary barrier design.",
    choices: {
      A: "Stick with traditional, battle-tested levees even if their protection ceiling is lower.",
      B: "Deploy the new experimental barrier at an active flood zone to test its potential.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  T5: {
    id: 'T5',
    dimension: 'T',
    phase: 'optional',
    context: 'Workplace technology',
    prompt: "A new generative AI tool cuts office paperwork in half, but occasionally outputs convincing mistakes.",
    choices: {
      A: "Roll it out across the company immediately, with human employees proofreading the drafts.",
      B: "Ban it from official workflows until its hallucination rate drops to near zero.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
};
