import { Dimension, DimensionMeta, Question } from './types';

export const DIMENSIONS: Dimension[] = ['M', 'A', 'I', 'G', 'E', 'T'];

export const DIMENSION_META: Record<Dimension, DimensionMeta> = {
  M: {
    id: 'M',
    name: 'Provision',
    score0End: 'Public provision',
    score100End: 'Markets',
    whatItDescribes: 'Preference for public delivery versus competing private providers in the scenarios shown.',
    whatItDoesNotEstablish: 'Whether the person wants an effective state, cares about poverty, or supports every business.',
    shareLineLow: 'Build in public hands',
    shareLineHigh: 'Let providers compete',
    strongTraitLow: 'PUBLIC PROVISION',
    strongTraitHigh: 'MARKETS',
    publicName: 'public services',
  },
  A: {
    id: 'A',
    name: 'Freedom',
    score0End: 'Social order',
    score100End: 'Autonomy',
    whatItDescribes: 'Willingness to protect individual choice when it imposes inconvenience, offence, or risk on others.',
    whatItDoesNotEstablish: 'Whether the person is kind, selfish, or approves of the protected behavior.',
    shareLineLow: 'Keep shared rules strong',
    shareLineHigh: 'Leave room for personal choice',
    strongTraitLow: 'SOCIAL ORDER',
    strongTraitHigh: 'AUTONOMY',
    publicName: 'personal freedom',
  },
  I: {
    id: 'I',
    name: 'Institutions',
    score0End: 'Challenge institutions',
    score100End: 'Trust institutions',
    whatItDescribes: 'Willingness to defer to established institutions versus seek outside checks or replacement.',
    whatItDoesNotEstablish: 'Expertise, support for democracy, conspiratorial beliefs, or state capacity.',
    shareLineLow: 'Make power earn your trust',
    shareLineHigh: 'Work through the institutions',
    strongTraitLow: 'INSTITUTIONAL SCEPTICISM',
    strongTraitHigh: 'INSTITUTIONAL TRUST',
    publicName: 'institutions',
  },
  G: {
    id: 'G',
    name: 'Belonging',
    score0End: 'National priority',
    score100End: 'Global concern',
    whatItDescribes: 'How much national membership should change cooperation, opportunity, and obligations.',
    whatItDoesNotEstablish: 'Ethnicity, personal tolerance, or feelings about every border policy.',
    shareLineLow: 'Responsibility starts at home',
    shareLineHigh: 'Look beyond the border',
    strongTraitLow: 'NATIONAL PRIORITY',
    strongTraitHigh: 'GLOBAL CONCERN',
    publicName: 'national priorities',
  },
  E: {
    id: 'E',
    name: 'Distribution',
    score0End: 'Unequal rewards',
    score100End: 'Equal outcomes',
    whatItDescribes: 'Preference for reducing differences in resources versus allowing rewards and inheritance to create larger differences.',
    whatItDoesNotEstablish: 'Work ethic, personal generosity, or belief that all inequality is deserved.',
    shareLineLow: 'Let the rewards differ',
    shareLineHigh: 'Close the gaps',
    strongTraitLow: 'UNEQUAL REWARDS',
    strongTraitHigh: 'EQUALITY',
    publicName: 'distribution',
  },
  T: {
    id: 'T',
    name: 'Change',
    score0End: 'Precaution',
    score100End: 'Acceleration',
    whatItDescribes: 'Willingness to introduce new technology under uncertainty versus wait for more evidence.',
    whatItDoesNotEstablish: 'Technical knowledge, support for a particular company, or confidence that technology always helps.',
    shareLineLow: 'Prove it before scaling it',
    shareLineHigh: 'Try it, watch it, learn',
    strongTraitLow: 'PRECAUTION',
    strongTraitHigh: 'ACCELERATION',
    publicName: 'technology',
  },
};

export const CORE_QUESTION_SEQUENCE: string[] = [
  'M1', 'A1', 'I1', 'G1', 'E1', 'T1',
  'M2', 'A2', 'I2', 'G2', 'E2', 'T2',
  'M3', 'A3', 'I3', 'G3', 'E3', 'T3',
];

export const QUESTION_BANK: Record<string, Question> = {
  // M: Provision
  M1: {
    id: 'M1',
    dimension: 'M',
    phase: 'core',
    context: 'Housing',
    prompt: "Housing has gotten too expensive for many people in your city. What is the best way to fix this?",
    choices: {
      A: "Cut building rules so private builders can build more homes quickly.",
      B: "Use government money to build affordable housing for people who need it.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  M2: {
    id: 'M2',
    dimension: 'M',
    phase: 'core',
    context: 'Transport',
    prompt: "The local trains are constantly late and overcrowded. How should they be run?",
    choices: {
      A: "Let one public agency run all trains so officials stay accountable to the public.",
      B: "Let private companies compete to run trains so prices go down and service improves.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  M3: {
    id: 'M3',
    dimension: 'M',
    phase: 'core',
    context: 'Internet',
    prompt: "High-speed internet in your area is expensive and often cuts out. What should be done?",
    choices: {
      A: "Treat internet like water or electricity, and build a city-run network for everyone.",
      B: "Cut rules and fees so private internet companies can compete and lower prices.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  M4: {
    id: 'M4',
    dimension: 'M',
    phase: 'optional',
    context: 'Childcare',
    prompt: "A city gets new money to make childcare cheaper for families. Where should that money go?",
    choices: {
      A: "Give cash vouchers directly to parents so they can pick any daycare they like.",
      B: "Use the money to open and expand free or low-cost city-run daycare centers.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  M5: {
    id: 'M5',
    dimension: 'M',
    phase: 'optional',
    context: 'Electricity',
    prompt: "A region needs to upgrade its power grid. How should electricity be generated and sold?",
    choices: {
      A: "Let private power companies compete with each other to sell electricity at market prices.",
      B: "Keep all power under one public utility with electricity prices set by elected officials.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },

  // A: Freedom
  A1: {
    id: 'A1',
    dimension: 'A',
    phase: 'core',
    context: 'Protest',
    prompt: "A peaceful protest march blocks a main highway during morning rush hour.",
    choices: {
      A: "Clear the road quickly so traffic and emergency vehicles can get through.",
      B: "Let the march continue, because protests need to disrupt things to be heard.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  A2: {
    id: 'A2',
    dimension: 'A',
    phase: 'core',
    context: 'Speech',
    prompt: "A public arts center books a performer whose show offends many people in the community.",
    choices: {
      A: "Let the show go on, because artists should be free to perform even if people are upset.",
      B: "Cancel the show, because tax money should not pay for offensive performances.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  A3: {
    id: 'A3',
    dimension: 'A',
    phase: 'core',
    context: 'Surveillance',
    prompt: "The city wants to put face-scanning cameras in busy public squares to track criminal suspects.",
    choices: {
      A: "Ban or restrict the cameras so innocent people are not constantly watched in public.",
      B: "Install the cameras to help police prevent crime and catch dangerous criminals.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  A4: {
    id: 'A4',
    dimension: 'A',
    phase: 'optional',
    context: 'Nightlife',
    prompt: "Late-night clubs and bars bring jobs and excitement to downtown, but keep nearby neighbors awake.",
    choices: {
      A: "Set strict nighttime quiet hours to protect residents' sleep and peace.",
      B: "Let bars and clubs stay open late to keep the city lively and support the nightlife economy.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  A5: {
    id: 'A5',
    dimension: 'A',
    phase: 'optional',
    context: 'Personal risk',
    prompt: "An extreme fighting sport causes a lot of serious, lifelong brain damage to its fighters.",
    choices: {
      A: "Pass laws to ban or heavily restrict the sport to protect people from permanent injury.",
      B: "Let adult fighters decide the risks for themselves, even if the sport is very dangerous.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },

  // I: Institutions
  I1: {
    id: 'I1',
    dimension: 'I',
    phase: 'core',
    context: 'Regulators',
    prompt: "The government health agency says a food ingredient is safe, but critics disagree.",
    choices: {
      A: "Trust the agency's decision and rely on official scientists and safety checks.",
      B: "Hold off until independent scientists outside the government test it and confirm it's safe.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  I2: {
    id: 'I2',
    dimension: 'I',
    phase: 'core',
    context: 'Political leadership',
    prompt: "Two candidates promise to fix how city hall is run. Who would you vote for?",
    choices: {
      A: "An outsider who isn't tied to the system and isn't afraid to challenge city officials.",
      B: "An experienced insider who knows how the system works and how to get things done.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  I3: {
    id: 'I3',
    dimension: 'I',
    phase: 'core',
    context: 'Agency leadership',
    prompt: "A city agency keeps failing to finish its building projects on time. What should change?",
    choices: {
      A: "Hire professional managers who have years of experience running government departments.",
      B: "Put a committee of local residents in charge so projects match neighborhood needs.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  I4: {
    id: 'I4',
    dimension: 'I',
    phase: 'optional',
    context: 'Accountability',
    prompt: "A big corruption scandal is uncovered inside city hall. Who should run the investigation?",
    choices: {
      A: "A panel of ordinary everyday citizens who have no ties to government workers.",
      B: "The official government watchdog agency that has legal powers and trained detectives.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  I5: {
    id: 'I5',
    dimension: 'I',
    phase: 'optional',
    context: 'Courts',
    prompt: "A high court cancels a popular new law because judges say it violates the constitution. Who gets the final word?",
    choices: {
      A: "The judges, because constitutional rules must protect minority rights even against a popular majority.",
      B: "The voters, because in a true democracy the majority of citizens must always have the final say.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },

  // G: Belonging
  G1: {
    id: 'G1',
    dimension: 'G',
    phase: 'core',
    context: 'Work',
    prompt: "A company has one job opening and two equally qualified applicants: a local citizen and a foreigner.",
    choices: {
      A: "Hire the local citizen first to support workers in your own country.",
      B: "Hire whichever person is best, because someone's nationality shouldn't matter for a job.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  G2: {
    id: 'G2',
    dimension: 'G',
    phase: 'core',
    context: 'Aid',
    prompt: "During a global disease outbreak, a life-saving medicine is in very short supply.",
    choices: {
      A: "Send medicine to the hardest-hit countries where people are dying, regardless of borders.",
      B: "Keep medicine for your own country's citizens first before sending any abroad.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  G3: {
    id: 'G3',
    dimension: 'G',
    phase: 'core',
    context: 'Cooperation',
    prompt: "A global climate treaty requires cutting pollution, but it will raise costs for local factories.",
    choices: {
      A: "Sign the treaty, because stopping global pollution requires every nation to work together.",
      B: "Refuse to sign, to protect local jobs and keep full control over your country's rules.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  G4: {
    id: 'G4',
    dimension: 'G',
    phase: 'optional',
    context: 'Refuge',
    prompt: "People escaping a war arrive at the border, but local towns are already running low on housing and clinics.",
    choices: {
      A: "Slow down entry so the number of new arrivals does not overwhelm local housing and clinics.",
      B: "Let them in immediately to save lives, and spend emergency money to shelter them.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  G5: {
    id: 'G5',
    dimension: 'G',
    phase: 'optional',
    context: 'Trade',
    prompt: "A city needs steel to build new bridges. Domestic steel costs 30% more than the exact same steel from abroad.",
    choices: {
      A: "Buy domestic steel to support factory jobs and businesses at home.",
      B: "Buy the cheaper imported steel to save taxpayers money and build more bridges.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },

  // E: Distribution
  E1: {
    id: 'E1',
    dimension: 'E',
    phase: 'core',
    context: 'Inheritance',
    prompt: "A wealthy person dies and leaves millions of dollars in property and money to their children.",
    choices: {
      A: "Take a large inheritance tax so that money can fund public schools, parks, and services.",
      B: "Let the children keep almost all the money, because parents have a right to pass what they earned to family.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  E2: {
    id: 'E2',
    dimension: 'E',
    phase: 'core',
    context: 'Rewards',
    prompt: "A team finishes a hard work project. Everyone helped, but two people did most of the work.",
    choices: {
      A: "Split the bonus money equally among all team members to reward teamwork.",
      B: "Give most of the bonus money to the two workers who did the heaviest work.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  E3: {
    id: 'E3',
    dimension: 'E',
    phase: 'core',
    context: 'Opportunity',
    prompt: "A top university has a few free scholarships to give to new students.",
    choices: {
      A: "Give them to the students with the highest test scores and best grades.",
      B: "Give them to smart students from poor families who cannot afford to attend.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  E4: {
    id: 'E4',
    dimension: 'E',
    phase: 'optional',
    context: 'Pay gaps',
    prompt: "A big company's chief executive makes several hundred times more money than the average worker.",
    choices: {
      A: "Pass a law capping top executive pay so workers and bosses don't have such extreme pay gaps.",
      B: "Let the company board decide pay based on what the executive is worth in the market.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  E5: {
    id: 'E5',
    dimension: 'E',
    phase: 'optional',
    context: 'Shared resources',
    prompt: "A town has extra money to spend on youth sports. How should the money be used?",
    choices: {
      A: "Hire elite coaches and build high-end facilities to help top young athletes succeed.",
      B: "Provide free sports programs and free equipment so every kid in town can play.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },

  // T: Change
  T1: {
    id: 'T1',
    dimension: 'T',
    phase: 'core',
    context: 'Transport technology',
    prompt: "Self-driving cars work well on test tracks, but haven't been tested much in busy city traffic.",
    choices: {
      A: "Start testing them on city streets now so the new technology can develop faster.",
      B: "Keep them on private test tracks until their safety is completely proven.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  T2: {
    id: 'T2',
    dimension: 'T',
    phase: 'core',
    context: 'Education technology',
    prompt: "An AI computer tutor helps students get higher test scores, but no one knows if it hurts their learning habits over time.",
    choices: {
      A: "Wait for long-term studies before allowing it into regular classrooms.",
      B: "Bring it into classrooms right away so students can get the learning benefits now.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  T3: {
    id: 'T3',
    dimension: 'T',
    phase: 'core',
    context: 'Food technology',
    prompt: "Meat grown in a lab passes basic government safety tests. Should grocery stores sell it?",
    choices: {
      A: "Yes, let stores sell it with clear labels and let shoppers decide for themselves.",
      B: "No, wait until multi-year health studies prove it has no long-term side effects.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
  T4: {
    id: 'T4',
    dimension: 'T',
    phase: 'optional',
    context: 'Infrastructure technology',
    prompt: "A coastal city is at risk of serious flooding. Engineers propose a brand-new, unproven sea wall design.",
    choices: {
      A: "Stick with traditional, proven flood walls that have worked reliably for decades.",
      B: "Build the experimental new design because it might protect the city much better.",
    },
    positiveChoice: 'B',
    discrimination: 1.2,
    threshold: 0,
  },
  T5: {
    id: 'T5',
    dimension: 'T',
    phase: 'optional',
    context: 'Workplace technology',
    prompt: "A new AI tool cuts office paperwork time in half, but it sometimes invents false facts with confidence.",
    choices: {
      A: "Let staff use the AI tool now and have humans double-check its work to save time.",
      B: "Ban the AI tool from important work until its makers can prove it doesn't make things up.",
    },
    positiveChoice: 'A',
    discrimination: 1.2,
    threshold: 0,
  },
};
